# Generated by Django 3.1.2 on 2020-10-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Codegnan User', 'verbose_name_plural': 'Codegnan Users'},
        ),
    ]
