# Generated by Django 3.1.2 on 2020-10-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0002_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
