# Generated by Django 3.1.2 on 2020-10-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0003_remove_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
