# Generated by Django 3.1.2 on 2020-10-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0005_auto_20201012_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
