# Generated by Django 3.1.2 on 2020-10-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0009_auto_20201014_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
