# Generated by Django 3.1.2 on 2020-10-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0011_auto_20201015_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
