# Generated by Django 3.1.2 on 2020-10-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0012_answer_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answerlabel',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='userlabel',
        ),
        migrations.AddField(
            model_name='question',
            name='answerlabel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='downvote',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='question',
            name='upvote',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='question',
            name='userlabel',
            field=models.CharField(default='Newcommer', max_length=50),
        ),
        migrations.DeleteModel(
            name='DownVote',
        ),
        migrations.DeleteModel(
            name='UpVote',
        ),
    ]
